from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^$', 'discSite.views.home', name='home'),
	url(r'^home/$', 'discSite.views.home', name='home'),
	url(r'^home/(?P<search_val>.+)/$', 'discSite.views.home', name='search'),
	url(r'^signup/$', 'discSite.views.signup', name='signup'),
	url(r'^signup_sub/$', 'discSite.views.signup_sub', name='signup_sub'),
	url(r'^login/$', 'discSite.views.login_home', name='login'),
	url(r'^login_submit/$', 'discSite.views.login_submit', name='login_submit'),
	url(r'^logout/$', 'discSite.views.logout', name='logout'),
	url(r'^contact_us/$', 'discSite.views.contact_us', name='contact_us'),
	url(r'^rules/$', 'discSite.views.rules', name='rules'),
	url(r'^account/$', 'discSite.views.account', name='account'),
	url(r'^item/$', 'discSite.views.home', name='item'),
	url(r'^watch_item/$', 'discSite.views.watch_item', name='watch_item'),
	url(r'^item/(?P<item_id>.+)/$', 'discSite.views.item', name='item'),
	url(r'^account/current_listings$', 'discSite.views.current_listings', name='current_listings'),
	url(r'^account/sold_listings$', 'discSite.views.sold_listings', name='sold_listings'),
	url(r'^account/expired_listings$', 'discSite.views.expired_listings', name='expired_listings'),
	url(r'^account/(?P<user_profile>.+)/$', 'discSite.views.user_page', name='user_page'),
	url(r'^accept_offer/$', 'discSite.views.accept_offer', name='accept_offer'),
	url(r'^account/$', 'discSite.views.user_page', name='user_page'),
	url(r'^relist/$', 'discSite.views.relist', name='relist'),
	url(r'^rate_user/$', 'discSite.views.rate_user', name='rate_user'),
	url(r'^del_listing/$', 'discSite.views.del_listing', name='del_listing'),
	url(r'^create_listing/$', 'discSite.views.create_listing', name='create_listing'),
)
